version: '3.8'

services:
  
  coffee-app:
    build:
      context: ../Coffee-shop          
      dockerfile: ./Dockerfile.coffee-app 
    environment:
      FEATURE_API_URL: http://feature-api:8080
    depends_on:
      - feature-api

  # Feature API
  feature-api:
    build:
      context: ../Feature-configuration
      dockerfile: ./Dockerfile.feature-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      # These variables come from the .env file
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: 8080

  # containerized Database
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      # These also come from the .env file
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

  # containerized Nginx
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - coffee-app
      - feature-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db-data: