name: Deployment CD

on:
  pull_request:
    branches:
      - main

jobs:
  call_ci:
    uses: ./.github/workflows/ci.yml

  deploy-with-ansible:
    runs-on: self-hosted
    needs: call_ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Ansible Docker Image
        run: |
          docker build -t ansible-runner .

      - name: Run Ansible Playbook in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ansible-runner \
            ansible-playbook -i Hosts.yaml playbook.yaml

  staging-deploy:
    runs-on: self-hosted
    needs: deploy-with-ansible
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging Environment..."

  integration-tests-staging:
    runs-on: self-hosted
    needs: staging-deploy
    steps:
      - name: Run Integration Tests on Staging
        run: echo "Running Integration Tests on Staging..."

  production-deploy:
    runs-on: self-hosted
    needs: integration-tests-staging
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment..."

  integration-tests-production:
    runs-on: self-hosted
    needs: production-deploy
    steps:
      - name: Run Integration Tests on Production
        run: echo "Running Integration Tests on Production..."
